# Generated by Django 5.2.8 on 2025-12-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_masage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default='', verbose_name='Содержание урока'),
            preserve_default=False,
        ),
    ]
